name: Gerar página estática

on:
  repository_dispatch:
    types: [gerar-pagina]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install -r app/requirements.txt

      - name: Rodar script Python
        env:
          TERM_BUSCA: ${{ github.event.client_payload.termo }}
        run: |
          echo "Rodando com termo: $TERM_BUSCA"
          python app/main.py "$TERM_BUSCA"

      - name: Deploy para o GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
