name: Gerar página estática

on:
  push:
    branches: [ "main" ]  # ou "master", dependendo do nome do seu branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install -r app/requirements.txt

      - name: Rodar script Python
        run: |
          python app/main.py

      - name: Configurar Git para deploy
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Criar a branch gh-pages e fazer push do HTML
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          mv output/* .  # Move o conteúdo de output para a raiz da branch gh-pages
          git add .
          git commit -m "Deploy da página estática"
          git push origin gh-pages --force
